# Generated by Django 4.0.4 on 2022-05-04 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_remove_bill_client_id_alter_bill_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='client_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crud.client'),
        ),
    ]
